baseURL = "https://lucid-borg-b0ac01.netlify.com"
languageCode = "en-us"
title = "Robeson Planetarium"
disableKinds = ["RSS"]
enableEmoji = true
log = true

[params]
    googleMapsApiKey = "AIzaSyB1L483vgdF-thHC9kDsBjDVF-L-98STIo"

[[menu.main]]
    name = "Home"
    weight = 1
    url = "/"

#[[menu.main]]
#    name = "School Calendar"
#    weight = 2
#    url = "/schoolcalendar/"
#    identifier = "schoolcalendar"

#[[menu.main]]
#    name = "Public Shows"
#    weight = 3
#    url = "/publicshows/"
#    identifier = "publicshows"

[[menu.main]]
    name = "Resources"
    weight = 4
    url = "/resources/"
    identifier = "resources"

#[[menu.main]]
#    name = "Science Center"
#    weight = 5
#    url = "/sciencecenter/"
#    identifier = "sciencecenter"

[[menu.main]]
    name = "Contact"
    weight = 6
    url = "/contact/"
    identifier = "contact"
    