backend:
  name: git-gateway
  branch: master
  repo: LauraBrandt/robeson-planetarium-hugo

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "news"
    label: "News Item (for homepage)"
    folder: "content/news"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "imageSRC", widget: "image", required: false}
      - {label: "Brief description of image", name: "imageALT", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
  - name: "schoolcalendar"
    label: "School Calendar"
    folder: "content/schoolcalendar/collection"
    create: true
    fields:
      - {label: "Date", name: "title", widget: "date"}
      - {label: "Event", name: "event", widget: "string"}
  - name: "publicshows"
    label: "Public Show"
    folder: "content/publicshows/collection"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}     
      - {label: "Upcoming or Previous?", name: "status", widget: "select", options: ["upcoming", "previous"]}
      - {label: "Date(s)/Time(s)", name: "showDates", widget: "text", required: false}       
      - {label: "Body", name: "body", widget: "markdown", required: false}
  - name: "resources"
    label: "Resource (either file or website)"
    folder: "content/resources/collection"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}   
      - {label: "Author", name: "author", widget: "string", required: false}
      - {label: "File", name: "fileLink", widget: "file", required: false}
      - {label: "Website", name: "website", widget: "string", required: false}
      - {label: "Type", name: "type", widget: "select", options: ["document", "pdf", "excel", "image", "mp3", "video", "zip", "website", "other"]}
      - {label: "Order to Appear in List", name: "weight", widget: "number", default: 1}
      - {label: "Description", name: "body", widget: "markdown", required: false}
  - name: "sciencecenter"
    label: "Science Center Exhibit"
    folder: "content/sciencecenter/collection"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "imageSRC", widget: "image", required: false}
      - {label: "Brief description of image", name: "imageALT", widget: "string", required: false}
      - {label: "Order to Appear in List", name: "weight", widget: "number", default: 1}
      - {label: "Description of Exhibit", name: "body", widget: "markdown", required: false}
  - name: "contact"
    label: "People on Contacts Page"
    folder: "content/contact/collection"
    create: true
    fields:    
      - {label: "Full Name", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Title/Position", name: "position", widget: "string"}
      - {label: "Phone Number", name: "phone", widget: "string", required: false}
      - {label: "Email", name: "email", widget: "string", required: false}
      - {label: "Profile Picture", name: "imageSRC", widget: "image", required: false}
      - {label: "Order to Appear in List", name: "weight", widget: "number", default: 1}
  - name: "posts"
    label: "Post"
    folder: "content/posts/collection"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown", required: false}